services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./db/clickhouse/data:/var/lib/clickhouse
      - ./db/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./db/clickhouse/log:/var/log/clickhouse-server/

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ancat
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"